<a href="https://colab.research.google.com/github/ShreeKeshavan/Numpy_Task/blob/main/Numpy_tasks_with_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__

'1.21.6'

In [ ]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x = np.array([10,20,30,40,50])
(x.size * x.itemsize)

40

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
np.arange(10,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
np.random.random((3,3,3))

array([[[0.32147931, 0.12617866, 0.02088223],
        [0.43325305, 0.56273101, 0.25187867],
        [0.25850541, 0.00818336, 0.98907858]],

       [[0.21580393, 0.96504501, 0.48388063],
        [0.87764991, 0.62986002, 0.4347673 ],
        [0.72409581, 0.22531605, 0.52702189]],

       [[0.93262435, 0.26452344, 0.28094417],
        [0.28648275, 0.03210741, 0.25160442],
        [0.69298192, 0.39690114, 0.97854115]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
np.random.random((10,10)).min()

0.016404998166669293

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
np.random.random(10).mean()

0.5783696478659148

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x = np.ones((10,10))
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x = np.ones((3,3))
np.pad(x, pad_width = 1, mode = 'constant', constant_values = 0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
np.diag([0,1,2,3,4])

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x = np.zeros((8,8),dtype = int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
x = np.array([[0,1],[1,0]])
y = np.tile(x,(4,4))
y

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.random((5,5))
ma, mi = x.max(), x.min()
y = (x - ma) / (ma - mi)
y

array([[-0.33471538, -0.99364203, -0.86155567, -0.5641678 , -0.98474396],
       [-0.9244218 , -0.35288135, -0.09671549, -0.91809753, -0.73591171],
       [-0.41376624, -0.84934996, -0.84842675, -0.11385763, -0.64800839],
       [-0.95772143, -1.        , -0.2763061 , -0.01961902, -0.92455897],
       [-0.23492551,  0.        , -0.41246717, -0.37080565, -0.58787822]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("R", np.ubyte, 1),
                  ("G", np.ubyte, 1),
                  ("B", np.ubyte, 1),
                  ("A", np.ubyte, 1)])
color

<ipython-input-24-3c9bf20abe2a>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("R", np.ubyte, 1),


dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
np.dot(np.ones((5,3),dtype =int), np.ones((3,2),dtype =int))

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x = np.arange(11)
x[(3 < x) & (x <= 8)] *= -1 
x

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
2 << Z >> 2, Z <- Z, 1j*Z, Z/1/1

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
[-9.22337204e+18]

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(x)), x))

[ 2.  6.  5.  5. -9. -1. -8. -7.  5.  5.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x = np.random.randint(0,10,10) 
y = np.random.randint(0,10,10)
print(np.intersect1d(x,y))

[3 4 5 6 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0  

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
x = np.datetime64('today','D') - np.timedelta64(1,'D')
y = np.datetime64('today','D')
z = np.datetime64('today','D') + np.timedelta64(1,'D')
print(x,y,z , sep ='\n')

2023-01-04
2023-01-05
2023-01-06


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
x = np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
x = np.ones(3) * 2
y = np.ones(3) * 4
z = np.ones(3) * 6
np.add(x,y,out = y)
np.divide(x,2,out = x)
np.negative(x, out = x)
np.multiply(x,y, out = x)

array([-6., -6., -6.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
 x = np.random.uniform(0,10,10)
 print(x - x%1)
 print(np.floor(x))
 print(np.ceil(x) - 1)
 print(x.astype(int))
 print(np.trunc(x))

[5. 1. 4. 3. 0. 5. 4. 7. 9. 7.]
[5. 1. 4. 3. 0. 5. 4. 7. 9. 7.]
[5. 1. 4. 3. 0. 5. 4. 7. 9. 7.]
[5 1 4 3 0 5 4 7 9 7]
[5. 1. 4. 3. 0. 5. 4. 7. 9. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x = np.zeros((5,5),dtype= int)
x += np.arange(5)
x

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
  for i in range(10):yield i 
y = np.fromiter(generate(), dtype = float, count = -1)
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
x = np.linspace(0,1,11,endpoint = False)[1:]
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x = np.random.random(10)
x.sort()
x

array([0.17228099, 0.17905544, 0.33356715, 0.47817522, 0.58507884,
       0.65571411, 0.73844448, 0.74903648, 0.75704866, 0.99960041])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
x = np.arange(10)
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
x = np.random.randint(0,2,5)
y = np.random.randint(0,2,5)
e = np.allclose(x,y)
print(e)
e = np.array_equal(x,y)
print(e)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
x = np.zeros(10)
x.flags.writeable = False


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
x = np.random.random((10,2))
y,z = x[:,0], x[:,1]
r = np.sqrt(y**2 + z**2)
t = np.arctan2(z,y)
print(r)
print(t)

[0.13804678 0.52164294 0.8962799  0.63181901 0.85338739 0.67312766
 0.9458519  0.99196554 0.82509567 0.4752176 ]
[0.98285329 0.77258034 0.52564653 1.27034481 0.20786117 1.26885292
 0.1331453  0.28878348 0.07008157 1.29474167]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x = np.random.random(10)
x[x.argmax()] = 0 
print(x)

[0.79351865 0.34221433 0.26423384 0.76527097 0.47446365 0.53030501
 0.52641229 0.07184874 0.8110441  0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
x = np.zeros((5,5),[('x',float),('y',float)])
x['x'],x['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
x

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x = np.arange(8)
y = x + 0.5 
c = 1.0 / np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32 , np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions()
x = np.zeros((16,16))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x = np.arange(100)
y = np.random.uniform(0,100)
index = (np.abs(x-y)).argmin()
print(x[index])

76


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
x = np.zeros(10,[('position',[('x', float, 1),
                              ('y', float, 1)]),
                 ('color',[('r',float,1),
                           ('g',float,1),
                           ('b',float,1)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-57-a09e702c813f>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.zeros(10,[('position',[('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
import scipy
import scipy.spatial
z = np.random.random((100,2))
d = scipy.spatial.distance.cdist(z,z)
print(d)

[[0.         0.03327075 0.39164117 ... 0.44263824 0.13721258 0.2457244 ]
 [0.03327075 0.         0.37977423 ... 0.44842125 0.13635549 0.25410625]
 [0.39164117 0.37977423 0.         ... 0.22887453 0.51353152 0.23302403]
 ...
 [0.44263824 0.44842125 0.22887453 ... 0.         0.57984595 0.19765494]
 [0.13721258 0.13635549 0.51353152 ... 0.57984595 0.         0.38285855]
 [0.2457244  0.25410625 0.23302403 ... 0.19765494 0.38285855 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
x = np.arange(10, dtype = np.float32)
x = x.astype(np.int32, copy = False)
x 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from numpy.lib.npyio import genfromtxt
from io import StringIO 
s = StringIO("""1, 2, 3, 4, 5\n6,  ,  , 7, 8\n ,  , 9,10,11\n""")
x = np.genfromtxt(s, delimiter=',', dtype=np.int)
print(x)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-61-88d4e89eef54>:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.genfromtxt(s, delimiter=',', dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
x = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(x):
  print(index, value)
for index in np.ndindex(x.shape):
  print(index, x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x + y*y)
sigma , mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / (2.0 * sigma**2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3 
x = np.zeros((n,n))
np.put(x,np.random.choice(range(n*n),p,replace = False),1)
print(x)

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x = np.random.rand(5,10)
y = x-x.mean(axis =1 , keepdims= True)
y = x-x.mean(axis=1).reshape(-1,1)
print(y)

[[ 0.19656966 -0.02028564  0.27765602  0.23335985 -0.60193013 -0.44362395
  -0.15362278  0.28374849  0.13879266  0.08933581]
 [-0.03538937  0.22845084  0.5628778   0.24141298  0.41410736 -0.27738297
  -0.38946012 -0.25474711 -0.28179198 -0.20807742]
 [ 0.19381861 -0.22308501 -0.03406706 -0.03685394  0.14448885 -0.28213036
  -0.17217195  0.45470044  0.05729229 -0.10199187]
 [-0.0775279   0.3105839   0.05864082  0.39892369 -0.06807185 -0.43858524
  -0.41134886 -0.01375656  0.54409687 -0.30295487]
 [ 0.17095419 -0.06886963 -0.46961609  0.14309605  0.08818469  0.12496176
  -0.19155714 -0.19988622 -0.02234103  0.42507342]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
x = np.random.randint(0,10,(3,3))
print(x)
print(x[x[:,1].argsort()])

[[0 4 4]
 [2 7 9]
 [7 4 8]]
[[0 4 4]
 [7 4 8]
 [2 7 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
x = np.random.randint(0,3,(3,10))
print((~x.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
x = np.random.uniform(0,1,10)
y = 0.5
m =x.flat[np.abs(x - y).argmin()]
print(m)

0.41790799610510365


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)
it = np.nditer([a,b,None])
for x,y,z in it:
   z[...] = x + y
print(it.operands[2]) 

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
x = np.ones(10)
i = np.random.randint(0,len(x),20)
x += np.bincount(i, minlength= len(x))
print(x)

[1. 5. 1. 3. 3. 5. 2. 5. 2. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
x = [1,2,3,4,5,6]
i = [1,3,9,3,4,1]
f =np.bincount(i,x)
print(f)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h = 16,16
i =np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
f = i[...,0]*(256*256) + i[...,1]*256 +i[...,2]
n = len(np.unique(f))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
sum =a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

3


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
import pandas as pd
d =np.random.uniform(0,1,100)
s = np.random.randint(0,101,100)
print(pd.Series(d).groupby(s).mean())

1      0.972362
2      0.878708
3      0.502404
4      0.139422
6      0.838648
12     0.816664
15     0.767457
16     0.611711
17     0.370477
18     0.896931
19     0.315936
20     0.756183
21     0.232673
23     0.446613
24     0.599601
25     0.758852
26     0.307538
28     0.627815
30     0.610117
32     0.445247
33     0.182670
34     0.817117
37     0.421104
41     0.230424
42     0.715871
48     0.886235
49     0.566974
52     0.381758
53     0.740327
54     0.561443
55     0.944682
56     0.637977
58     0.277358
60     0.808965
65     0.441128
67     0.615389
68     0.412969
69     0.360047
74     0.051297
76     0.295233
78     0.438972
79     0.502898
80     0.437069
81     0.663120
82     0.522357
83     0.930390
84     0.368524
86     0.359946
87     0.513875
89     0.332324
90     0.376795
91     0.358328
92     0.609268
93     0.320040
94     0.225314
96     0.635230
97     0.077887
99     0.900648
100    0.658994
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
a = np.random.uniform(0,1,(5,5))
b = np.random.uniform(0,1,(5,5))
print(np.sum(a * b.T, axis=1))

[0.4287436  0.62692141 1.5994752  1.44019066 1.56684388]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
x = np.array([1,2,3,4,5])
nz = 3
y = np.zeros(len(x) + (len(x)-1)*(nz))
y[::nz+1] = x
print(y)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
a = np.ones((5,5,3))
b = 2*np.ones((5,5))
print(a * b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
f = np.roll(faces.repeat(2,axis=1),-1,axis=1)
f = f.reshape(len(f)*3,2)
f = np.sort(f,axis=1)
g = f.view( dtype=[('p0',f.dtype),('p1',f.dtype)])
g = np.unique(g)
print(g)

[( 0, 16) ( 0, 87) ( 2, 20) ( 2, 94) ( 4,  4) ( 4, 40) ( 9, 19) ( 9, 91)
 (14, 54) (14, 76) (16, 87) (19, 32) (19, 44) (19, 91) (20, 94) (28, 87)
 (28, 92) (32, 44) (40, 43) (40, 46) (43, 46) (45, 48) (45, 87) (48, 87)
 (54, 76) (54, 80) (54, 89) (80, 89) (87, 92)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
c = np.bincount([1,1,2,3,4,4,6])
a = np.repeat(np.arange(len(c)),c)
print(a)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3):
  ret = np.cumsum(a, dtype=float)
  ret[n:] = ret[n:] - ret[:-n]
  return ret[n -1:] / n
z = np.arange(20)
print(moving_average(z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks
def rolling(a, window):
  shape = (a.size - window + 1, window)
  strides = (a.itemsize, a.itemsize)
  return stride_tricks.as_strided(a, shape=shape,strides=strides)
z = rolling(np.arange(10),3)
print(z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.54329893, -0.67474967, -0.17222885, -0.15826696, -0.75529358,
       -0.12184033, -0.67297811,  0.48840122, -0.49343699, -0.8788439 ,
       -0.05037564,  0.75800219, -0.98563767,  0.67444689,  0.23103709,
       -0.85082837,  0.37539203,  0.49820465,  0.69328532, -0.05761572,
       -0.83079028,  0.3000304 ,  0.09733464,  0.53997249,  0.85830285,
        0.81826083,  0.89374692,  0.008205  , -0.14643639, -0.80021056,
       -0.62505411, -0.10686259,  0.48819276,  0.63210436, -0.66244087,
        0.14268145, -0.09704234, -0.23504218, -0.88677543,  0.83232846,
        0.14052606,  0.67694154,  0.95466752,  0.62254341, -0.98558467,
        0.02655946,  0.54183357, -0.17713183,  0.57770441,  0.94944693,
        0.51092858, -0.42912287, -0.59490265, -0.15563046, -0.1136125 ,
        0.59710053,  0.56584013, -0.93268838, -0.46589248, -0.20171551,
       -0.78550212, -0.4261355 , -0.30970394,  0.44208307,  0.76579457,
       -0.09584093, -0.95504079,  0.86778028, -0.55586625,  0.01

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[2.96678826 2.07314858 9.85086002 2.58967566 1.20323989 1.45265329
 3.56509643 7.13647461 7.02002304 1.54770439]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 9.77674882 11.30405797 12.85256341  2.80801766  3.9046585   1.6216006
  11.50216524  5.18061817  8.66143531  1.33227838]
 [ 0.46822235  5.60877179  4.52334237  4.01115145  3.84734425  5.56205732
   5.88315009  0.10327282  3.48685774  1.62794986]
 [15.64744846  5.44882339  5.68429095 10.20463287  9.94993263 17.64764101
   3.69020297 11.35571372  9.4329456  14.20691478]
 [ 0.62218887  4.36249579  6.39711392 11.17923578 11.99645332  5.36159886
   9.7477932  11.76565731 11.82231623  8.63127782]
 [ 0.20478973  3.26793106  5.30104498 11.58871862 12.33437762  5.46863826
   8.84918087 11.80200131 11.37906702  8.79811352]
 [14.72569879 14.27054675 15.47988895  2.30050261  1.1306892   6.2774864
  11.20601827  0.6815819   5.72717901  3.44174954]
 [12.78245703 13.10888036 14.45170328  0.29227008  0.8491234   4.44579214
  11.32728537  2.45192184  6.88424285  1.56387641]
 [ 1.61616514  1.20950108  3.22155294 12.14637196 12.75104336  5.4380209
   7.01415405 11.63658881 10.32581157  8.88228158]
 [1

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 6 4 0 3 3 6 3 9 1]
 [2 2 4 3 7 0 4 1 6 6]
 [3 8 3 0 2 1 4 0 4 0]
 [8 6 1 0 5 3 7 7 9 2]
 [2 1 8 5 2 2 1 1 7 3]
 [2 4 9 2 7 2 5 0 6 0]
 [8 5 9 3 4 0 7 9 0 3]
 [7 2 3 8 2 7 3 6 2 6]
 [7 9 0 7 1 5 1 1 3 0]
 [7 1 1 4 9 7 7 0 9 0]]
[[0 0 0 0 0]
 [0 8 6 4 0]
 [0 2 2 4 3]
 [0 3 8 3 0]
 [0 8 6 1 0]]


<ipython-input-87-f2b5781f38bf>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 1 2]
   [0 0 4]
   [3 3 3]]

  [[1 2 1]
   [0 4 4]
   [3 3 4]]

  [[2 1 3]
   [4 4 2]
   [3 4 2]]

  [[1 3 4]
   [4 2 0]
   [4 2 3]]

  [[3 4 2]
   [2 0 4]
   [2 3 2]]

  [[4 2 0]
   [0 4 4]
   [3 2 1]]

  [[2 0 0]
   [4 4 1]
   [2 1 3]]

  [[0 0 2]
   [4 1 4]
   [1 3 0]]]


 [[[0 0 4]
   [3 3 3]
   [4 2 1]]

  [[0 4 4]
   [3 3 4]
   [2 1 1]]

  [[4 4 2]
   [3 4 2]
   [1 1 1]]

  [[4 2 0]
   [4 2 3]
   [1 1 1]]

  [[2 0 4]
   [2 3 2]
   [1 1 2]]

  [[0 4 4]
   [3 2 1]
   [1 2 1]]

  [[4 4 1]
   [2 1 3]
   [2 1 3]]

  [[4 1 4]
   [1 3 0]
   [1 3 4]]]


 [[[3 3 3]
   [4 2 1]
   [1 3 3]]

  [[3 3 4]
   [2 1 1]
   [3 3 1]]

  [[3 4 2]
   [1 1 1]
   [3 1 0]]

  [[4 2 3]
   [1 1 1]
   [1 0 1]]

  [[2 3 2]
   [1 1 2]
   [0 1 4]]

  [[3 2 1]
   [1 2 1]
   [1 4 2]]

  [[2 1 3]
   [2 1 3]
   [4 2 4]]

  [[1 3 0]
   [1 3 4]
   [2 4 2]]]


 [[[4 2 1]
   [1 3 3]
   [2 0 2]]

  [[2 1 1]
   [3 3 1]
   [0 2 0]]

  [[1 1 1]
   [3 1 0]
   [2 0 2]]

  [[1 1 1]
   [1 0 1]
   [0 2 3]]

  [[1 1 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5 10 10  9  9]
 [10  7  4 11  3]
 [10  4  4 42  4]
 [ 9 11 42  3 11]
 [ 9  3  4 11  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):

    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [114]:
Z = np.array([1, 2, 3, 4, 5])
Z_cubed = np.power(Z, 3)
Z_cubed

Z = np.array([1, 2, 3, 4, 5])
Z_cubed = np.multiply(Z, np.multiply(Z, Z))
Z_cubed

Z = np.array([1, 2, 3, 4, 5])
Z_cubed = np.einsum("i,i,i->i", Z, Z, Z)
Z_cubed

array([  1,   8,  27,  64, 125])

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 3 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 3 3]
 [0 1 0]
 [1 0 4]
 [0 0 4]
 [1 4 0]
 [1 2 1]
 [1 1 2]
 [2 3 4]
 [3 4 4]
 [2 3 0]]
[[0 3 3]
 [0 1 0]
 [1 0 4]
 [0 0 4]
 [1 4 0]
 [1 2 1]
 [1 1 2]
 [2 3 4]
 [3 4 4]
 [2 3 0]]
[[0 3 3]
 [0 1 0]
 [1 0 4]
 [0 0 4]
 [1 4 0]
 [1 2 1]
 [1 1 2]
 [2 3 4]
 [3 4 4]
 [2 3 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 4]
 [0 1 0]
 [0 3 3]
 [1 0 4]
 [1 1 2]
 [1 2 1]
 [1 4 0]
 [2 3 0]
 [2 3 4]
 [3 4 4]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B) 

array([[0.23410323, 0.11701333, 0.04324591, 0.22295964, 0.12677395,
        0.25628836, 0.30122659, 0.10846137, 0.29091991, 0.07253233],
       [0.65734882, 0.32856691, 0.1214321 , 0.62605823, 0.35597417,
        0.71964341, 0.84582745, 0.30455346, 0.81688687, 0.20366674],
       [0.6143382 , 0.30706863, 0.11348674, 0.58509496, 0.33268262,
        0.67255683, 0.79048459, 0.2846264 , 0.7634376 , 0.19034073],
       [0.27682369, 0.13836658, 0.05113766, 0.26364655, 0.14990836,
        0.30305728, 0.35619609, 0.128254  , 0.34400859, 0.08576843],
       [0.34949386, 0.17468977, 0.06456203, 0.33285753, 0.18926144,
        0.38261414, 0.44970264, 0.1619225 , 0.43431575, 0.10828387],
       [0.62938687, 0.31459051, 0.11626669, 0.5994273 , 0.34083193,
        0.68903161, 0.8098481 , 0.29159853, 0.78213858, 0.19500327],
       [0.23153183, 0.11572805, 0.04277089, 0.22051063, 0.12538145,
        0.25347327, 0.29791789, 0.10727002, 0.28772442, 0.07173563],
       [0.06149045, 0.03073517, 0.0113591

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.11851929  0.23362296]
